Okazaki p2 diagnosis dict 518
NCI-GDC/gdcdictionary pull request #1083
Opened 2024-08-29 17:53 UTC by bullenc

2024-08-29 19:10 UTC, wwysoc2 requested changes

2024-08-29 19:10 UTC, wwysoc2 commented on src/gdcdictionary/schemas/diagnosis.yaml
> +        - Rete testis
Capitalize, I'll change the JIRA

2024-08-29 19:10 UTC, wwysoc2 commented on src/gdcdictionary/schemas/diagnosis.yaml
> +        - Tunica albuginea
Capitalize, I'll change the JIRA

2024-08-29 19:10 UTC, wwysoc2 commented on src/gdcdictionary/schemas/diagnosis.yaml
> +        - Tunica vaginalis
Capitalize, I'll change the JIRA

2024-08-29 19:55 UTC, bullenc commented on src/gdcdictionary/schemas/diagnosis.yaml
> +        - Rete testis
updated 👍

2024-08-29 19:55 UTC, bullenc commented on src/gdcdictionary/schemas/diagnosis.yaml
> +        - Tunica albuginea
updated 👍

2024-08-29 19:55 UTC, bullenc commented on src/gdcdictionary/schemas/diagnosis.yaml
> +        - Tunica vaginalis
updated 👍

2024-08-29 20:22 UTC, ebusygina approved these changes

2024-08-29 21:25 UTC, ProfOak approved these changes

2024-08-29 21:30 UTC, stilesj-uchicago approved these changes
LGTM

2024-08-30 04:18 UTC, wteouchicago approved these changes

2024-08-30 15:21 UTC, wwysoc2 approved these changes
👍 lgtm!

2024-08-30 15:23 UTC, merged