New Feat/dict 54 to resolve issues with migrated properties
NCI-GDC/gdcdictionary pull request #839
Opened 2020-12-03 16:58 UTC by tlicht3

In an effort to clean up the diagnosis node, I have removed the properties that have been migrated to the pathology detail node. See this node for migration details: https://jira.opensciencedatacloud.org/browse/DAT-2890

2020-12-03 19:40 UTC, ganjigajanan commented
@tlicht3 `peritoneal_fluid_cytological_status` seems to be removed along with `peripancreatic_lymph_nodes_tested` could you please add it back. that will fix the failing tests.

2020-12-03 19:43 UTC, ganjigajanan commented
Also please update the _terms.yaml file to remove any references to those deleted properties   which are specific to diagnosis node. it will not cause failure if we do not remove them, but will remain as junk otherwise.

2020-12-03 20:27 UTC, wwysoc2 requested changes

2020-12-03 20:27 UTC, wwysoc2 commented on gdcdictionary/examples/valid/diagnosis.json
> +    "peritoneal_fluid_cytological_status": "Atypical"
Add a comma after "Atypical"

2020-12-03 22:46 UTC, tlicht3 commented on gdcdictionary/examples/valid/diagnosis.json
> +    "peritoneal_fluid_cytological_status": "Atypical"
This has been updated.

2020-12-04 14:30 UTC, wwysoc2 approved these changes

2020-12-04 14:42 UTC, merged