Updated molecular test yaml
NCI-GDC/gdcdictionary pull request #933
Opened 2023-01-17 18:06 UTC by wwysoc2

https://jira.opensciencedatacloud.org/browse/DICT-233

2023-01-17 20:46 UTC, bullenc requested changes

2023-01-17 20:46 UTC, bullenc commented on gdcdictionary/schemas/molecular_test.yaml
> +      - Not Amplified
I think these need to be alphabetized?

2023-01-17 20:56 UTC, bullenc commented on gdcdictionary/schemas/molecular_test.yaml
> +      - Not Amplified
🙌

2023-01-18 16:21 UTC, sadhukd approved these changes
Looks good.

2023-01-19 00:54 UTC, wteouchicago approved these changes
looks good

2023-01-20 16:14 UTC, bullenc reviewed
Looks great 👍

2023-01-20 17:10 UTC, mpsolano approved these changes

2023-01-20 22:08 UTC, tlicht3 approved these changes

2023-01-23 15:14 UTC, bullenc approved these changes

2023-01-23 15:27 UTC, merged