update sample node DICT-235
NCI-GDC/gdcdictionary pull request #935
Opened 2023-01-17 18:37 UTC by bullenc

2023-01-17 20:39 UTC, wwysoc2 requested changes
I think I only found some things that need alphabetizing.

2023-01-17 20:39 UTC, wwysoc2 commented on gdcdictionary/schemas/sample.yaml
> +      - New Primary
Alphabetize this one.

2023-01-17 20:39 UTC, wwysoc2 commented on gdcdictionary/schemas/sample.yaml
> +      - Bone Marrow NOS
Alphabetize this and below.

2023-01-17 20:55 UTC, bullenc commented on gdcdictionary/schemas/sample.yaml
> +      - Bone Marrow NOS
alphabetized 👍

2023-01-17 20:59 UTC, bullenc commented on gdcdictionary/schemas/sample.yaml
> +      - New Primary
also alphabetized

2023-01-19 01:02 UTC, wteouchicago approved these changes
looks good

2023-01-19 22:58 UTC, ProfOak approved these changes

2023-01-19 23:01 UTC, ProfOak approved these changes

2023-01-23 16:40 UTC, wwysoc2 approved these changes

2023-01-23 17:21 UTC, merged